"""Update db

Revision ID: 186cfec3778f
Revises: 27bf2aa3b8c7
Create Date: 2025-03-01 15:22:13.620091

"""

from alembic import op
import sqlalchemy as sa

from app.model.base import CustomUUID

# revision identifiers, used by Alembic.
revision = "186cfec3778f"
down_revision = "27bf2aa3b8c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("id", CustomUUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_team_id"), "team", ["id"], unique=False)
    op.add_column("employee", sa.Column("team_id", CustomUUID(), nullable=True))
    op.create_foreign_key(None, "employee", "team", ["team_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "employee", type_="foreignkey")
    op.drop_column("employee", "team_id")
    op.drop_index(op.f("ix_team_id"), table_name="team")
    op.drop_table("team")
    # ### end Alembic commands ###
