"""update_table_vacation

Revision ID: 6fa0a3133c4d
Revises: 6e2c9f09a980
Create Date: 2025-03-01 20:42:01.772129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa0a3133c4d'
down_revision = '6e2c9f09a980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation', sa.Column('paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation', 'paid')
    # ### end Alembic commands ###
